exit 1 in case of user interrupt
git-svn-id: https://svn.nfit.au.dk/svn/beta/trunk@4147 678b6752-a8a0-49ff-a511-7c2a3241fcd4

diff --git a/bin_unix/exectool b/bin_unix/exectool
--- a/bin_unix/exectool
+++ b/bin_unix/exectool
@@ -43,13 +43,17 @@ fi
 
 # execute
 
+# trap user interrupt - exit 1 in this case:
+# in case this script was invoked from a make file or perl
+# this will stop make/perl too.
+
 trap "echo ''; echo 'User Interrupt'; \
 if [  '$BETASTAT' = 'yes' -a -w $STATFILE ]; \
 then \
 echo 'interrupt:  ' `whoami` '|' $MACHINETYPE '|' `hostname` '|' `date` '|' $$ '|' $* code\(130\) \
 >> $STATFILE; \
 fi; \
-exit 0\
+exit 1\
 " 2
 
 touch $ERRFILE
@@ -241,7 +245,8 @@ rm -f $ERRFILE
 
 esac
 
-# give an appropriate exit code
+# give an appropriate exit code - see trap for user inteerupt above
+# for motivation for this.
 case $STATUS in
 NORMAL)
     exit 0;;
