minor details
git-svn-id: https://svn.nfit.au.dk/svn/beta/trunk@4120 678b6752-a8a0-49ff-a511-7c2a3241fcd4

diff --git a/bin_unix/exectool b/bin_unix/exectool
--- a/bin_unix/exectool
+++ b/bin_unix/exectool
@@ -187,7 +187,8 @@ then
 		then
 		    LINE1=`head -1 "$EXECNAME".dump  | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g'`
 		    LINE5=`head -5 "$EXECNAME".dump | tail -1 | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g' `
-		    echo '<br><a href="http:'$REPORTNO'.html"> '$TODAY' '$REPORTNO  `whoami` '</a><br>' $LINE1 '<br>' $LINE5 '<br>' >>$TOOLINDEX
+		    LINE6=`head -6 "$EXECNAME".dump | tail -1 | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g' `
+		    echo '<br> '$TODAY' <a href="http:'$REPORTNO'.html"> '$REPORTNO '</a>  `whoami` <br>' $LINE1 '<br>' $LINE5 '<br>' $LINE6 '<br>' >>$TOOLINDEX
 
 		fi
 	    fi
@@ -239,4 +240,14 @@ fi
 
 rm -f $ERRFILE
 
+esac
+
+# give an appropriate exit code
+case $STATUS in
+NORMAL)
+    exit 0;;
+INTERRUPT)
+    exit 1;;
+*)
+    exit 1;;
 esac
