bug: used tee's exit code instead
git-svn-id: https://svn.nfit.au.dk/svn/beta/trunk@7287 678b6752-a8a0-49ff-a511-7c2a3241fcd4

diff --git a/bin_unix/exectool b/bin_unix/exectool
--- a/bin_unix/exectool
+++ b/bin_unix/exectool
@@ -59,15 +59,16 @@ exit 1\
 touch $ERRFILE
 if [ -w $ERRFILE ] 
 then
-	$LOCATION/$EXECNAME $DEFAULTOPTIONS $* 2>&1 | tee $ERRFILE
+	#hack to collect exit code from $EXECNAME instead of tee:
+	sh -c "$LOCATION/$EXECNAME $DEFAULTOPTIONS $*; NUMSTAT=\$?; echo exitcode:>>$ERRFILE; echo \$NUMSTAT>>$ERRFILE " 2>&1 | tee $ERRFILE
+	NUMSTAT=`tail -1 $ERRFILE`
 else
 	$LOCATION/$EXECNAME $DEFAULTOPTIONS $* 
+	NUMSTAT=$?
 fi
 
 
 # check status
-
-NUMSTAT=$?
 
 case $NUMSTAT in
 0)	STATUS="NORMAL"
@@ -166,14 +167,14 @@ then
 
         echo ""
         echo "****** ${EXECNAME} has exited with fatal error ******"
-	echo We are sorry about that and will try to correct the error as soon 
-	echo as possible. In order to find the cause of the error we need your help. 
+	echo In order to find the cause of the error we need your help. 
 	echo Please enter a short description of the situation leading to the crash.
-	echo "That description will be mailed to the developer(s) of ${EXECNAME}"
-	echo The dump file will automatically be included in the mail, but any
-	echo further information e.g. consol output is appreciated.
-	echo If you do not have the time to the explain the error or if you already
-	echo "have described it previously, then just type ^D"
+	echo "That description will be mailed to the developer(s) of ${EXECNAME}."
+	echo The dump file will automatically be included in the mail,
+	echo but any further information e.g. consol output is appreciated.
+	echo If you do not have the time to the explain the error,
+	echo "or if you already have described it previously, "
+	echo "then just type ^D"
 	echo ""
         echo "Stop by typing ^D:"
 	cat		   >> $TMPFILE
@@ -213,12 +214,21 @@ then
 	    fi
 
 	    echo "(no dumpfile)"             >> $TMPFILE
-	    if [ -w $ERRFILE ] 
-	    then 
-		cat $ERRFILE  | head -500 >> $TMPFILE
-	    fi
+	    
         fi
+
         echo "----------"                  >> $TMPFILE
+        echo ""            >> $TMPFILE
+
+        if [ -w $ERRFILE ] 
+	then 
+            echo "Output:"                  >> $TMPFILE
+            echo "----------"                  >> $TMPFILE
+	    cat $ERRFILE  | head -500 >> $TMPFILE
+	fi
+
+        echo "----------"                  >> $TMPFILE
+        echo ""            >> $TMPFILE
 
 	if  [ "$BETAREPORT_EMAIL" = "yes" ]
 	then
